name: CI
on: [push, pull_request]

jobs:
  build:
    name: CI (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Setup Scala CLI
        run: |
          sudo curl -Lo /usr/bin/scala-cli https://raw.githubusercontent.com/VirtusLab/scala-cli/main/scala-cli.sh && \
          sudo chmod +x /usr/bin/scala-cli

      - name: test
        run: make test

      - name: package
        env:
          RELEASE_MODE: release-fast
        run: |
          export BUILD_SUFFIX=$(scala-cli -e 'println("-" + com.indoorvivants.detective.Platform.os.coursierString)' -d com.indoorvivants.detective::platform:0.0.2)
          make lsp

      - uses: actions/upload-artifact@v3
        with:
          name: binaries 
          path: bin/LLVM_LanguageServer* 
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  release:
    needs: [build]
    name: Release
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Download binaries
        uses: actions/download-artifact@v2
        id: download
        with:
          path: binaries

      - run: ls -lR binaries


