name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - uses: VirtusLab/scala-cli-setup@main

      - name: test
        run: scala-cli test .

      - name: package
        run: scala-cli package . --native -f -o LLVM_LanguageServer
