name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: CI (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - uses: VirtusLab/scala-cli-setup@main

      - name: test
        run: make test

      - name: package
        run: |
          set -e
          export RELEASE_MODE=$(scala-cli build/script.scala -- release-mode)
          export BUILD_SUFFIX=$(scala-cli build/script.scala -- build-suffix)
          make lsp

      - uses: actions/upload-artifact@v3
        with:
          name: binaries 
          path: bin/LLVM_LanguageServer* 
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  release:
    needs: [build]
    name: Release
    if: startsWith(github.ref, 'refs/tags/v') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Download binaries
        uses: actions/download-artifact@v2
        id: download
        with:
          path: binaries

      - run: ls -lR binaries

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{steps.download.outputs.download-path}}/**/*"
